/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAttachmentDialog: typeof import('./src/components/unit/AddAttachmentDialog.vue')['default']
    AddUnitDialog: typeof import('./src/components/order/AddUnitDialog.vue')['default']
    ArchiveStats: typeof import('./src/components/stats/ArchiveStats.vue')['default']
    AssignModal: typeof import('./src/components/order/AssignModal.vue')['default']
    CloneMasterFiles: typeof import('./src/components/unit/CloneMasterFiles.vue')['default']
    CollectionAddDialog: typeof import('./src/components/metadata/CollectionAddDialog.vue')['default']
    CollectionBulkAdd: typeof import('./src/components/related/CollectionBulkAdd.vue')['default']
    CollectionRecords: typeof import('./src/components/related/CollectionRecords.vue')['default']
    ComponentsResults: typeof import('./src/components/results/ComponentsResults.vue')['default']
    CreateProjectDialog: typeof import('./src/components/unit/CreateProjectDialog.vue')['default']
    DataDisplay: typeof import('./src/components/DataDisplay.vue')['default']
    FormField: typeof import('./src/components/FormField.vue')['default']
    HathiTrustDialog: typeof import('./src/components/metadata/HathiTrustDialog.vue')['default']
    HathiTrustMetadataDialog: typeof import('./src/components/order/HathiTrustMetadataDialog.vue')['default']
    HathiTrustUpdateDialog: typeof import('./src/components/HathiTrustUpdateDialog.vue')['default']
    ImageStats: typeof import('./src/components/stats/ImageStats.vue')['default']
    InvoiceDialog: typeof import('./src/components/order/InvoiceDialog.vue')['default']
    LocationUnitsDialog: typeof import('./src/components/metadata/LocationUnitsDialog.vue')['default']
    LookupDialog: typeof import('./src/components/LookupDialog.vue')['default']
    MasterFiles: typeof import('./src/components/component/MasterFiles.vue')['default']
    MasterFilesList: typeof import('./src/components/unit/MasterFilesList.vue')['default']
    MasterFilesResults: typeof import('./src/components/results/MasterFilesResults.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    MetadataResults: typeof import('./src/components/results/MetadataResults.vue')['default']
    MetadataStats: typeof import('./src/components/stats/MetadataStats.vue')['default']
    NewMetadataPanel: typeof import('./src/components/metadata/NewMetadataPanel.vue')['default']
    OrdersResults: typeof import('./src/components/results/OrdersResults.vue')['default']
    RelatedMasterFiles: typeof import('./src/components/related/RelatedMasterFiles.vue')['default']
    RelatedOrders: typeof import('./src/components/related/RelatedOrders.vue')['default']
    RelatedUnits: typeof import('./src/components/related/RelatedUnits.vue')['default']
    RelatedUnitsDialog: typeof import('./src/components/unit/RelatedUnitsDialog.vue')['default']
    RenumberDialog: typeof import('./src/components/unit/RenumberDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHelpPopover: typeof import('./src/components/SearchHelpPopover.vue')['default']
    SearchIndexPopover: typeof import('./src/components/SearchIndexPopover.vue')['default']
    SearchResults: typeof import('./src/components/results/SearchResults.vue')['default']
    SendEmailDialog: typeof import('./src/components/order/SendEmailDialog.vue')['default']
    SimilarImages: typeof import('./src/components/results/SimilarImages.vue')['default']
    StorageStats: typeof import('./src/components/stats/StorageStats.vue')['default']
    TagsDialog: typeof import('./src/components/masterfile/TagsDialog.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UMain: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UnitsResults: typeof import('./src/components/results/UnitsResults.vue')['default']
    UvaLibraryLogo: typeof import('./src/components/UvaLibraryLogo.vue')['default']
    WaitSpinner: typeof import('./src/components/WaitSpinner.vue')['default']
  }
}
